// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `payment_raw_message_data.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct RawMessageData {
    // message fields
    pub raw_message_data_type: RawMessageDataType,
    pub raw_message_data: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RawMessageData {
    fn default() -> &'a RawMessageData {
        <RawMessageData as ::protobuf::Message>::default_instance()
    }
}

impl RawMessageData {
    pub fn new() -> RawMessageData {
        ::std::default::Default::default()
    }

    // .protobuf.payment.RawMessageDataType raw_message_data_type = 1;


    pub fn get_raw_message_data_type(&self) -> RawMessageDataType {
        self.raw_message_data_type
    }
    pub fn clear_raw_message_data_type(&mut self) {
        self.raw_message_data_type = RawMessageDataType::RawMessageDataType_NotSet;
    }

    // Param is passed by value, moved
    pub fn set_raw_message_data_type(&mut self, v: RawMessageDataType) {
        self.raw_message_data_type = v;
    }

    // string raw_message_data = 2;


    pub fn get_raw_message_data(&self) -> &str {
        &self.raw_message_data
    }
    pub fn clear_raw_message_data(&mut self) {
        self.raw_message_data.clear();
    }

    // Param is passed by value, moved
    pub fn set_raw_message_data(&mut self, v: ::std::string::String) {
        self.raw_message_data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_raw_message_data(&mut self) -> &mut ::std::string::String {
        &mut self.raw_message_data
    }

    // Take field
    pub fn take_raw_message_data(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.raw_message_data, ::std::string::String::new())
    }
}

impl ::protobuf::Message for RawMessageData {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.raw_message_data_type, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.raw_message_data)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.raw_message_data_type != RawMessageDataType::RawMessageDataType_NotSet {
            my_size += ::protobuf::rt::enum_size(1, self.raw_message_data_type);
        }
        if !self.raw_message_data.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.raw_message_data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.raw_message_data_type != RawMessageDataType::RawMessageDataType_NotSet {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.raw_message_data_type))?;
        }
        if !self.raw_message_data.is_empty() {
            os.write_string(2, &self.raw_message_data)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RawMessageData {
        RawMessageData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RawMessageDataType>>(
                "raw_message_data_type",
                |m: &RawMessageData| { &m.raw_message_data_type },
                |m: &mut RawMessageData| { &mut m.raw_message_data_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "raw_message_data",
                |m: &RawMessageData| { &m.raw_message_data },
                |m: &mut RawMessageData| { &mut m.raw_message_data },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RawMessageData>(
                "RawMessageData",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RawMessageData {
        static instance: ::protobuf::rt::LazyV2<RawMessageData> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RawMessageData::new)
    }
}

impl ::protobuf::Clear for RawMessageData {
    fn clear(&mut self) {
        self.raw_message_data_type = RawMessageDataType::RawMessageDataType_NotSet;
        self.raw_message_data.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RawMessageData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RawMessageData {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum RawMessageDataType {
    RawMessageDataType_NotSet = 0,
    Form3PaymentAdmission = 1,
    SapPostingResponse = 2,
    JWTResponse = 3,
}

impl ::protobuf::ProtobufEnum for RawMessageDataType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RawMessageDataType> {
        match value {
            0 => ::std::option::Option::Some(RawMessageDataType::RawMessageDataType_NotSet),
            1 => ::std::option::Option::Some(RawMessageDataType::Form3PaymentAdmission),
            2 => ::std::option::Option::Some(RawMessageDataType::SapPostingResponse),
            3 => ::std::option::Option::Some(RawMessageDataType::JWTResponse),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [RawMessageDataType] = &[
            RawMessageDataType::RawMessageDataType_NotSet,
            RawMessageDataType::Form3PaymentAdmission,
            RawMessageDataType::SapPostingResponse,
            RawMessageDataType::JWTResponse,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<RawMessageDataType>("RawMessageDataType", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for RawMessageDataType {
}

impl ::std::default::Default for RawMessageDataType {
    fn default() -> Self {
        RawMessageDataType::RawMessageDataType_NotSet
    }
}

impl ::protobuf::reflect::ProtobufValue for RawMessageDataType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1epayment_raw_message_data.proto\x12\x10protobuf.payment\"\x93\x01\n\
    \x0eRawMessageData\x12W\n\x15raw_message_data_type\x18\x01\x20\x01(\x0e2\
    $.protobuf.payment.RawMessageDataTypeR\x12rawMessageDataType\x12(\n\x10r\
    aw_message_data\x18\x02\x20\x01(\tR\x0erawMessageData*w\n\x12RawMessageD\
    ataType\x12\x1d\n\x19RawMessageDataType_NotSet\x10\0\x12\x19\n\x15Form3P\
    aymentAdmission\x10\x01\x12\x16\n\x12SapPostingResponse\x10\x02\x12\x0f\
    \n\x0bJWTResponse\x10\x03BF\n-uk.co.nationwide.payments.schema.payment.b\
    odyB\x15PaymentRawMessageDatab\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
