// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `payment_identifiers.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct Identifiers {
    // message fields
    pub payment_id: ::std::string::String,
    pub urn: ::std::string::String,
    pub unique_scheme_id: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Identifiers {
    fn default() -> &'a Identifiers {
        <Identifiers as ::protobuf::Message>::default_instance()
    }
}

impl Identifiers {
    pub fn new() -> Identifiers {
        ::std::default::Default::default()
    }

    // string payment_id = 1;


    pub fn get_payment_id(&self) -> &str {
        &self.payment_id
    }
    pub fn clear_payment_id(&mut self) {
        self.payment_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_payment_id(&mut self, v: ::std::string::String) {
        self.payment_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_payment_id(&mut self) -> &mut ::std::string::String {
        &mut self.payment_id
    }

    // Take field
    pub fn take_payment_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.payment_id, ::std::string::String::new())
    }

    // string urn = 2;


    pub fn get_urn(&self) -> &str {
        &self.urn
    }
    pub fn clear_urn(&mut self) {
        self.urn.clear();
    }

    // Param is passed by value, moved
    pub fn set_urn(&mut self, v: ::std::string::String) {
        self.urn = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_urn(&mut self) -> &mut ::std::string::String {
        &mut self.urn
    }

    // Take field
    pub fn take_urn(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.urn, ::std::string::String::new())
    }

    // string unique_scheme_id = 3;


    pub fn get_unique_scheme_id(&self) -> &str {
        &self.unique_scheme_id
    }
    pub fn clear_unique_scheme_id(&mut self) {
        self.unique_scheme_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_unique_scheme_id(&mut self, v: ::std::string::String) {
        self.unique_scheme_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_unique_scheme_id(&mut self) -> &mut ::std::string::String {
        &mut self.unique_scheme_id
    }

    // Take field
    pub fn take_unique_scheme_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.unique_scheme_id, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Identifiers {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.payment_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.urn)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.unique_scheme_id)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.payment_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.payment_id);
        }
        if !self.urn.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.urn);
        }
        if !self.unique_scheme_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.unique_scheme_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.payment_id.is_empty() {
            os.write_string(1, &self.payment_id)?;
        }
        if !self.urn.is_empty() {
            os.write_string(2, &self.urn)?;
        }
        if !self.unique_scheme_id.is_empty() {
            os.write_string(3, &self.unique_scheme_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Identifiers {
        Identifiers::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "payment_id",
                |m: &Identifiers| { &m.payment_id },
                |m: &mut Identifiers| { &mut m.payment_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "urn",
                |m: &Identifiers| { &m.urn },
                |m: &mut Identifiers| { &mut m.urn },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "unique_scheme_id",
                |m: &Identifiers| { &m.unique_scheme_id },
                |m: &mut Identifiers| { &mut m.unique_scheme_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Identifiers>(
                "Identifiers",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Identifiers {
        static instance: ::protobuf::rt::LazyV2<Identifiers> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Identifiers::new)
    }
}

impl ::protobuf::Clear for Identifiers {
    fn clear(&mut self) {
        self.payment_id.clear();
        self.urn.clear();
        self.unique_scheme_id.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Identifiers {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Identifiers {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19payment_identifiers.proto\x12\x10protobuf.payment\"h\n\x0bIdentifi\
    ers\x12\x1d\n\npayment_id\x18\x01\x20\x01(\tR\tpaymentId\x12\x10\n\x03ur\
    n\x18\x02\x20\x01(\tR\x03urn\x12(\n\x10unique_scheme_id\x18\x03\x20\x01(\
    \tR\x0euniqueSchemeIdBC\n-uk.co.nationwide.payments.schema.payment.bodyB\
    \x12PaymentIdentifiersb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
